language: csharp
solution: QFramework.sln
script: 
    - sh ./build.sh 
    - sh ./test.sh 
sudo: true 

# Blacklist
branches:
    except:
    - master


# Enviroment variables
env:
    global:
        - GH_REPO_NAME: QFramework
        - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
        - GH_REPO_REF: github.com/liangxiegame/QFramework.git


addons:
    apt:
        packages:
            - doxygen
            - doxygen-doc
            - doxygen-latex
            - doxygen-gui
            - graphviz

# Build your code e.g. by calling make
    - make
# Generate and deploy documentation
    - cd $TRAVIS_BUILD_DIR
    - chmod +x generateDocumentationAndDeploy.sh
    - ./generateDocumentationAndDeploy.sh

