language: csharp
language: python

solution: QFramework.sln

sudo: true 

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: QFramework
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
    - GH_REPO_REF: github.com/liangxiegame/QFramework.git


# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script: 
    - sh ./build.sh 
    - sh ./test.sh 

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh

